name: Angular build

on:
  workflow_call:
    inputs:
      app-name:
        required: true
        type: string
      release-build:
        description: 'Indicates if this is a release build. Uploads artifact when true'
        required: false
        type: boolean
        default: false
      has-playwright:
        description: 'Determines if app has a playwright tests that should be run'
        required: false
        type: boolean
        default: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup .Node.js LTS
      uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm ci
    - name: Lint
      if: ${{ success() }}
      run: npm run lint
    - name: Build
      if: ${{ success() }}
      run: npm run build:ci
    - name: Test
      if: ${{ success() }}
      run: npm run test:ci
    - name: Install Playwright Browsers
      if: ${{ success() && inputs.has-playwright }}
      run: npx playwright install chromium --with-deps
    - name: Run Playwright tests
      if: ${{ success() && inputs.has-playwright }}
      run: npx playwright test
    - name: Upload Playwright report
      if: ${{ success() && inputs.has-playwright }}
      uses: actions/upload-artifact@v4
      with:
        name: playwright-report
        path: playwright/results
        retention-days: 30
    - name: Upload a Build Artifact
      if: ${{ success() && inputs.release-build }}
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.app-name }}
        path: dist/**
        if-no-files-found: error

