name: dotnet-api-build-test-publish

on:
  workflow_call:
    inputs:
      api-name:
        required: true
        type: string
      do-checkout:
        description: 'Whether the checkout step should be performed'
        required: false
        type: boolean
        default: true
      do-upload:
        description: 'Whether the upload build artifact step should be performed'
        required: false
        type: boolean
        default: true

jobs:
  build-test-publish:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      if: ${{ inputs.do-checkout }}
      uses: actions/checkout@v4.1.1
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Publish
      run: dotnet publish ${{ inputs.api-name }}/${{ inputs.api-name }}.csproj -c Release -o dist
    - name: Upload a Build Artifact
      if: ${{ success() && inputs.do-upload }}
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.api-name }}
        path: dist/**
        if-no-files-found: error
