name: linux-vps-deploy-run

on:
  workflow_call:
    inputs:
      application-name:
        required: true
        type: string
      host:
        required: true
        type: string
      username:
        required: true
        type: string
      ssh-key:
        required: true
        type: string
      ssh-passphrase:
        required: true
        type: string

jobs:
  deploy-run:
  
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Create dist folder
      run: mkdir ~/dist
      
    - name: Download artifact
      uses: actions/download-artifact@v3
      with:
        name: ${{ inputs.application-name }}
        path: dist
    
    - name: Stop service
      uses: appleboy/ssh-action@master
      with:
        host: ${{ inputs.host }}
        username: ${{ inputs.username }}
        key: ${{ inputs.ssh-key }}
        passphrase: ${{ inputs.ssh-passphrase }}
        script: | 
          sudo systemctl stop kestrel-${{ inputs.application-name }}.service
          
    - name: Copy artifact via scp
      uses: appleboy/scp-action@master
      with:
        host: ${{ inputs.host }}
        username: ${{ inputs.username }}
        key: ${{ inputs.ssh-key }}
        passphrase: ${{ inputs.ssh-passphrase }}
        strip_components: 1
        source: "dist/*"
        target: "../../var/www/${{ inputs.application-name }}"

    - name: Start service
      uses: appleboy/ssh-action@master
      with:
        host: ${{ inputs.host }}
        username: ${{ inputs.username }}
        key: ${{ inputs.ssh-key }}
        passphrase: ${{ inputs.ssh-passphrase }}
        script: | 
          sudo systemctl start kestrel-${{ inputs.application-name }}.service
          sudo systemctl status kestrel-${{ inputs.application-name }}.service
